{"text": "2021-07-12T16:47:10.251485+0000 ERROR An error has been caught in function 'dispatch', process 'MainProcess' (104), thread 'ThreadPoolExecutor-0_0' (140316868806400):\nTraceback (most recent call last):\n\n  File \"/usr/local/lib/python3.8/threading.py\", line 890, in _bootstrap\n    self._bootstrap_inner()\n    \u2502    \u2514 <function Thread._bootstrap_inner at 0x7f9e17644e50>\n    \u2514 <Thread(ThreadPoolExecutor-0_0, started daemon 140316868806400)>\n  File \"/usr/local/lib/python3.8/threading.py\", line 932, in _bootstrap_inner\n    self.run()\n    \u2502    \u2514 <function Thread.run at 0x7f9e17644b80>\n    \u2514 <Thread(ThreadPoolExecutor-0_0, started daemon 140316868806400)>\n  File \"/usr/local/lib/python3.8/threading.py\", line 870, in run\n    self._target(*self._args, **self._kwargs)\n    \u2502    \u2502        \u2502    \u2502        \u2502    \u2514 {}\n    \u2502    \u2502        \u2502    \u2502        \u2514 <Thread(ThreadPoolExecutor-0_0, started daemon 140316868806400)>\n    \u2502    \u2502        \u2502    \u2514 (<weakref at 0x7f9e1126b680; to 'ThreadPoolExecutor' at 0x7f9e17590280>, <_queue.SimpleQueue object at 0x7f9e175a14f0>, None,...\n    \u2502    \u2502        \u2514 <Thread(ThreadPoolExecutor-0_0, started daemon 140316868806400)>\n    \u2502    \u2514 <function _worker at 0x7f9e17597af0>\n    \u2514 <Thread(ThreadPoolExecutor-0_0, started daemon 140316868806400)>\n  File \"/usr/local/lib/python3.8/concurrent/futures/thread.py\", line 80, in _worker\n    work_item.run()\n    \u2502         \u2514 <function _WorkItem.run at 0x7f9e17597c10>\n    \u2514 <concurrent.futures.thread._WorkItem object at 0x7f9e112dbd30>\n  File \"/usr/local/lib/python3.8/concurrent/futures/thread.py\", line 57, in run\n    result = self.fn(*self.args, **self.kwargs)\n             \u2502    \u2502   \u2502    \u2502       \u2502    \u2514 {}\n             \u2502    \u2502   \u2502    \u2502       \u2514 <concurrent.futures.thread._WorkItem object at 0x7f9e112dbd30>\n             \u2502    \u2502   \u2502    \u2514 []\n             \u2502    \u2502   \u2514 <concurrent.futures.thread._WorkItem object at 0x7f9e112dbd30>\n             \u2502    \u2514 functools.partial(<bound method SyncToAsync.thread_handler of <asgiref.sync.SyncToAsync object at 0x7f9e1286f040>>, <_UnixSel...\n             \u2514 <concurrent.futures.thread._WorkItem object at 0x7f9e112dbd30>\n  File \"/usr/local/lib/python3.8/site-packages/asgiref/sync.py\", line 462, in thread_handler\n    return func(*args, **kwargs)\n           \u2502     \u2502       \u2514 {}\n           \u2502     \u2514 (functools.partial(<function convert_exception_to_response.<locals>.inner at 0x7f9e1286ad30>, <ASGIRequest: POST '/api/ad/cre...\n           \u2514 <built-in method run of Context object at 0x7f9e100b8200>\n  File \"/usr/local/lib/python3.8/site-packages/django/core/handlers/exception.py\", line 47, in inner\n    response = get_response(request)\n               \u2502            \u2514 <ASGIRequest: POST '/api/ad/create'>\n               \u2514 <debug_toolbar.middleware.DebugToolbarMiddleware object at 0x7f9e1286cf40>\n  File \"/usr/local/lib/python3.8/site-packages/debug_toolbar/middleware.py\", line 48, in __call__\n    return self.get_response(request)\n           \u2502    \u2502            \u2514 <ASGIRequest: POST '/api/ad/create'>\n           \u2502    \u2514 <function convert_exception_to_response.<locals>.inner at 0x7f9e1286a670>\n           \u2514 <debug_toolbar.middleware.DebugToolbarMiddleware object at 0x7f9e1286cf40>\n  File \"/usr/local/lib/python3.8/site-packages/django/core/handlers/exception.py\", line 47, in inner\n    response = get_response(request)\n               \u2502            \u2514 <ASGIRequest: POST '/api/ad/create'>\n               \u2514 <debug_toolbar_force.middleware.ForceDebugToolbarMiddleware object at 0x7f9e1286cd00>\n  File \"/usr/local/lib/python3.8/site-packages/debug_toolbar_force/middleware.py\", line 30, in __call__\n    response = self.get_response(request)\n               \u2502    \u2502            \u2514 <ASGIRequest: POST '/api/ad/create'>\n               \u2502    \u2514 <asgiref.sync.AsyncToSync object at 0x7f9e1286c580>\n               \u2514 <debug_toolbar_force.middleware.ForceDebugToolbarMiddleware object at 0x7f9e1286cd00>\n  File \"/usr/local/lib/python3.8/site-packages/asgiref/sync.py\", line 201, in __call__\n    current_executor.run_until_future(loop_future)\n    \u2502                \u2502                \u2514 <Future at 0x7f9e112e56d0 state=running>\n    \u2502                \u2514 <function CurrentThreadExecutor.run_until_future at 0x7f9e175961f0>\n    \u2514 <asgiref.current_thread_executor.CurrentThreadExecutor object at 0x7f9e12834df0>\n  File \"/usr/local/lib/python3.8/site-packages/asgiref/current_thread_executor.py\", line 62, in run_until_future\n    work_item.run()\n    \u2502         \u2514 <function _WorkItem.run at 0x7f9e175960d0>\n    \u2514 <asgiref.current_thread_executor._WorkItem object at 0x7f9e112a59d0>\n  File \"/usr/local/lib/python3.8/site-packages/asgiref/current_thread_executor.py\", line 22, in run\n    result = self.fn(*self.args, **self.kwargs)\n             \u2502    \u2502   \u2502    \u2502       \u2502    \u2514 {}\n             \u2502    \u2502   \u2502    \u2502       \u2514 <asgiref.current_thread_executor._WorkItem object at 0x7f9e112a59d0>\n             \u2502    \u2502   \u2502    \u2514 ()\n             \u2502    \u2502   \u2514 <asgiref.current_thread_executor._WorkItem object at 0x7f9e112a59d0>\n             \u2502    \u2514 functools.partial(<bound method SyncToAsync.thread_handler of <asgiref.sync.SyncToAsync object at 0x7f9e112a5ca0>>, <_UnixSel...\n             \u2514 <asgiref.current_thread_executor._WorkItem object at 0x7f9e112a59d0>\n  File \"/usr/local/lib/python3.8/site-packages/asgiref/sync.py\", line 462, in thread_handler\n    return func(*args, **kwargs)\n           \u2502     \u2502       \u2514 {}\n           \u2502     \u2514 (functools.partial(<function AdCreateView at 0x7f9e1298f430>, <ASGIRequest: POST '/api/ad/create'>),)\n           \u2514 <built-in method run of Context object at 0x7f9e12875140>\n  File \"/usr/local/lib/python3.8/site-packages/django/views/decorators/csrf.py\", line 54, in wrapped_view\n    return view_func(*args, **kwargs)\n           \u2502          \u2502       \u2514 {}\n           \u2502          \u2514 (<ASGIRequest: POST '/api/ad/create'>,)\n           \u2514 <function AdCreateView at 0x7f9e1298f3a0>\n  File \"/usr/local/lib/python3.8/site-packages/django/views/generic/base.py\", line 70, in view\n    return self.dispatch(request, *args, **kwargs)\n           \u2502    \u2502        \u2502         \u2502       \u2514 {}\n           \u2502    \u2502        \u2502         \u2514 ()\n           \u2502    \u2502        \u2514 <ASGIRequest: POST '/api/ad/create'>\n           \u2502    \u2514 <function APIView.dispatch at 0x7f9e1623c3a0>\n           \u2514 <ad.views.AdCreateView object at 0x7f9e112a5f10>\n> File \"/usr/local/lib/python3.8/site-packages/rest_framework/views.py\", line 506, in dispatch\n    response = handler(request, *args, **kwargs)\n               \u2502       \u2502         \u2502       \u2514 {}\n               \u2502       \u2502         \u2514 ()\n               \u2502       \u2514 <rest_framework.request.Request: POST '/api/ad/create'>\n               \u2514 <bound method AdCreateView.post of <ad.views.AdCreateView object at 0x7f9e112a5f10>>\n\n  File \"/usr/src/Backend_DRF_v2/ad/views.py\", line 95, in post\n    ad = author_ad.create(\n         \u2502         \u2514 <function QuerySet.create at 0x7f9e166f5ca0>\n         \u2514 <QuerySet []>\n\n  File \"/usr/local/lib/python3.8/site-packages/django/db/models/query.py\", line 451, in create\n    obj = self.model(**kwargs)\n          \u2502    \u2502       \u2514 {'title': '\u041e\u0431\u044a\u044f\u0432\u043b\u0435\u043d\u0438\u0435 1', 'author': <User: \u0412\u043b\u0430\u0434\u0438\u0441\u043b\u0430\u0432>, 'geolocation': '', 'city': 2, 'number_of_person': 4, 'number_of_girls'...\n          \u2502    \u2514 <class 'ad.models.Ad'>\n          \u2514 <QuerySet []>\n  File \"/usr/local/lib/python3.8/site-packages/django/db/models/base.py\", line 498, in __init__\n    _setattr(self, prop, kwargs[prop])\n    \u2502        \u2502     \u2502     \u2502      \u2514 'participants'\n    \u2502        \u2502     \u2502     \u2514 {'participants': <User: \u0412\u043b\u0430\u0434\u0438\u0441\u043b\u0430\u0432>}\n    \u2502        \u2502     \u2514 'participants'\n    \u2502        \u2514 <Ad: \u041e\u0431\u044a\u044f\u0432\u043b\u0435\u043d\u0438\u0435 1>\n    \u2514 <built-in function setattr>\n  File \"/usr/local/lib/python3.8/site-packages/django/db/models/fields/related_descriptors.py\", line 545, in __set__\n    raise TypeError(\n\nTypeError: Direct assignment to the forward side of a many-to-many set is prohibited. Use participants.set() instead.\n", "record": {"elapsed": {"repr": "0:00:10.703687", "seconds": 10.703687}, "exception": {"type": "TypeError", "value": "Direct assignment to the forward side of a many-to-many set is prohibited. Use participants.set() instead.", "traceback": true}, "extra": {}, "file": {"name": "views.py", "path": "/usr/local/lib/python3.8/site-packages/rest_framework/views.py"}, "function": "dispatch", "level": {"icon": "\u274c", "name": "ERROR", "no": 40}, "line": 506, "message": "An error has been caught in function 'dispatch', process 'MainProcess' (104), thread 'ThreadPoolExecutor-0_0' (140316868806400):", "module": "views", "name": "rest_framework.views", "process": {"id": 104, "name": "MainProcess"}, "thread": {"id": 140316868806400, "name": "ThreadPoolExecutor-0_0"}, "time": {"repr": "2021-07-12 16:47:10.251485+00:00", "timestamp": 1626108430.251485}}}
